version: "3.7"
services:
  # MySQL Database
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  
  # Spring Boot Application
  achat-app:
    image: jihedai/achat:1.0.0
    ports:
      - "8083:8083"
    environment:
     SPRING_APPLICATION_JSON: '{"spring.datasource.url":"jdbc:mysql://mysqldb:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username":"root", "spring.datasource.password":null, "spring.jpa.hibernate.ddl-auto":"update", "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5InnoDBDialect"}'
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data: