version: "3.7"
services:
  # MySQL Database
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: achatdb 
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  
  # Spring Boot Application
  achat-app:
    image: jihedai/achat-app
    ports:
      - "8083:8083"
    environment:
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
          "spring.datasource.username": "root",
          "spring.datasource.password": "",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }

    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data: